### ISSUE TITLE
Utrust checkout option not showing with Woocommerce

### ISSUE THREAD

**Issue by flazaldo** [utrustdev/utrust-for-woocommerce#5]
Hi, I just installed Utrust for Woocommerce (sandbox version), did all the setup as per instructed, including adding the API key and Webhook secret. However when I go to checkout I do not see Utrust payment option (I just see the credit card and Paypal payment options as before). I have a bunch of plugins on my site, including Aelia Currency Switcher and Wordfence for security. I do not see any issue mentioned with these plugins. Do you have any suggestions as to how I can get Utrust to work? 

Many thanks
Mark

<img width="939" alt="Screenshot 2021-01-02 at 19 47 56" src="https://user-images.githubusercontent.com/11591043/103469498-b2996400-4d33-11eb-902c-2387eab1f40e.png">
<img width="750" alt="Screenshot 2021-01-02 at 19 47 01" src="https://user-images.githubusercontent.com/11591043/103469501-b62ceb00-4d33-11eb-8ace-e22cacb3c0fd.png">

**Comment by nunoapfernandes** [comment]
Hello Mark.

In order to help you, can you provide us your PHP version, WooCommerce version and the logs ?

Best regards.

**Comment by flazaldo** [comment]
Thanks for your reply.
PHP version: 7.3.25
Woocommerce version: 4.8.0

In terms of the logs, do you mean WooCommerce logs? When I look in there they are empty. If not, where do I find the logs you need?

Many thanks for your assistance, Mark

**Comment by nunoapfernandes** [comment]
Glad to help :)

The logs I'm looking for are these.

> All the changes there will be reflected live in the store. Check the Utrust logs in the Admin Dashboard, in WooCommerce > Status > Logs, and search for the file utrust-for-woocommerce<random_hash>.log. If something went wrong in this plugin, the error message should be in there.

If you don't see logs from Utrust plugin, it could mean the plugin is not even loaded.

You've also mentioned Aelia Currency Switcher. Have you enabled Utrust for the currencies as specified [here](https://aelia.freshdesk.com/support/solutions/articles/158712-one-or-more-payment-methods-don-t-appear-after-installing-the-currency-switcher-how-can-i-fix-it-) ? 
You can also confirm this quickly by disabling Currency Switcher for a quick test.
 
Best regards!

**Comment by flazaldo** [comment]
I had indeed not enabled Utrust for Aelia. I've now done so and all is working! Thank you so much for your help.
Best wishes, Mark

**Comment by flazaldo** [comment]
Oh, one other question if I may... rather than converting any payments received to GBP and sending it to my bank account, am I able to keep the cryptocurrency and instead transfer this to my private wallet? Thanks, Mark

**Comment by nunoapfernandes** [comment]
Good to hear you could sort it out.

As of now, we only support crypto to fiat payments, but we have crypto to crypto on our roadmap. Feel free to follow us on our social media to get more news about it when it happens https://support.utrust.com/en/articles/4388060-is-utrust-on-social-media
